### ISSUE TITLE
wrong links to docker compose files in install

### ISSUE THREAD

**Issue by ThetaGamma** [archanchoudhury/SOC-OpenSource#2]
Nice idea, but it fails in the first step as the link to the compose file for ELK is not working

https://github.com/archanchoudhury/SOC-OpenSource/blob/main/installation/install1.md:

`wget https://raw.githubusercontent.com/archanchoudhury/SOC-OpenSource/main/codes/elk/docker-compose.yml?token=AMFWN76WO6EJP3LVF5DVHNLBWN7KQ`
 404 not found

**Comment by archanchoudhury** [comment]
Hi, Thanks for reaching out. Yes, we had removed our custom script for
Elastic. So it wont work. Please check the official Elastic repo for ELK
installation. They have individual plus docker code as well.
