### ISSUE TITLE
Elastic Components are not Open Source

### ISSUE THREAD

**Issue by defensivedepth** [archanchoudhury/SOC-OpenSource#3]
Great work on this project!

Unfortunately, the Elastic Components used are not open source - 

Directly from Elastic:

`Does this mean that Elasticsearch and Kibana are no longer Open Source?`

`Yes. Neither the Elastic License nor SSPL have been approved by the OSI, so to prevent confusion, we no longer refer to Elasticsearch or Kibana as open source. We updated our website and our messaging to refer to these products as “Free & Open,” and when talking about the licenses directly, we describe them as “source-available.” If you notice an area we missed, please let us know, so we can correct it.`

https://www.elastic.co/pricing/faq/licensing#does-this-mean-that-elasticsearch-and-kibana-are-no-longer-open-source

**Comment by archanchoudhury** [comment]
Thanks for the note.
But "Free and Open" still works for the implementation. 😊
