### ISSUE TITLE
Original Install.md has been removed

### ISSUE THREAD

**Issue by Network-Sec** [archanchoudhury/SOC-OpenSource#4]
</Nevermind>

**Comment by archanchoudhury** [comment]
Hi,

Thanks for reaching out. The details step was redundant and its anyway was
the same steps written in the components official git repo. I had removed
them to keep the originality of the creators intact. There is nothing extra
in installing, but steps are required only to make them integrated with
each other. So the video can be followed to achieve that. 😊

There are more works being done in terms of EDR, attack defence lab,
containarization of the whole stack, etc.. Stay Tuned!

**Comment by Network-Sec** [comment]
Nevermind, can be closed. Found it in some fork.
