### ISSUE TITLE
Elastic setup

### ISSUE THREAD

**Issue by qtip27** [archanchoudhury/SOC-OpenSource#5]
Having a issue with the wget request. I couldn't find where to change the user name and password. If the screenshot doesn't work, this is what I am getting:

wget https://raw.githubusercontent.com/archanchoudhury/SOC-OpenSource/main/codes/elk/docker-compose.yml?token=AMFWN76WO6EJP3LVF5DVHNLBWN7KQ
--2022-02-20 19:56:26--  https://raw.githubusercontent.com/archanchoudhury/SOC-OpenSource/main/codes/elk/docker-compose.yml?token=AMFWN76WO6EJP3LVF5DVHNLBWN7KQ
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-02-20 19:56:26 ERROR 404: Not Found.

![Screenshot from 2022-02-20 14-22-42](https://user-images.githubusercontent.com/88595204/154862828-a70065d0-f3d8-46cf-ba2b-c31167385475.png)

If you all need more info, please let me know. Thank you.

**Comment by archanchoudhury** [comment]
Hi, Thanks for raising this issue. Yes, we are aware of this issue. We have removed the custom code from the repo to maintain integrity and valuation of our creation. 
Still, you can find the code from Elastic official repo. Otherwise, if you need any freelance support do let us know.
