### ISSUE TITLE
ERROR 404 ON DOCKER-COMPOSE.YML

### ISSUE THREAD

**Issue by jotaah123** [archanchoudhury/SOC-OpenSource#8]
in the first phase of installation, the link is dead ( https://raw.githubusercontent.com/archanchoudhury/SOC-OpenSource/main/codes/elk/docker-compose.yml?token=AMFWN76WO6EJP3LVF5DVHNLBWN7KQ"

**Comment by archanchoudhury** [comment]
The custom code has been removed from repo due to having propitiatory information. You can refer to Elastic Official repo for downloading Elastic-Kibana
